server.port=8082

spring.application.name=rh-service

# Database - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rh_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=myerp_user
spring.datasource.password=myerp_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.registry-fetch-interval-seconds=30
eureka.client.instance-info-replication-interval-seconds=30
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

# Configuração de Logs
logging.level.com.exemplo.ponto=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
