services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: myerp-postgres
    environment:
      POSTGRES_DB: myerp_db
      POSTGRES_USER: postgres       # <- agora o superusuário padrão
      POSTGRES_PASSWORD: postgres   # <- senha do superusuário
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - myerp-network

  # pgAdmin (opcional - interface web para PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: myerp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@myerp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - myerp-network

volumes:
  postgres_data:

networks:
  myerp-network:
    driver: bridge
